### ISSUE TITLE
服务器启动时Mixin注入失败导致服务器无法启动

### ISSUE THREAD

**Issue by 1343008086** [MCTeamPotato/Better-End-Potato-Edition#1]
服务端：catserver1.16.5
mod版本：2.11.1
```
Exception in thread "main" [23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.reflect.InvocationTargetException
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.reflect.Method.invoke(Method.java:498)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at foxlaunch.FoxServerLauncher.main(FoxServerLauncher.java:33)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at catserver.server.CatServerLaunch.main(CatServerLaunch.java:8)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[23:39:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         ... 6 more
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.reflect.InvocationTargetException
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:644]:      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:644]:      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:644]:      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:644]:      at java.lang.reflect.Method.invoke(Method.java:498)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:644]:      at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:644]:      at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:644]:      ... 13 more
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      at net.minecraft.server.Main.main(Main.java:103)[23:39:45] [main/INFO]: [java.lang.Throwable:printStackTrace:668]:      ... 19 more
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method be_modifyTickState(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/BlockState;)Lnet/minecraft/block/BlockState; in betterendforge.mixins.json:common.ServerLevelMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap betterendforge.refmap.json
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[23:39:45] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      ... 30 more
```

**Comment by Kasualix** [comment]
https://github.com/Luohuayu/CatServer/issues/862

**Comment by Kasualix** [comment]
看起来是catserver的asm跟咱的mixin冲了，我不太懂asm，在他们修复前你要不先用纯forge？

**Comment by 1343008086** [comment]
好的

**Comment by 1343008086** [comment]
我想知道在哪个版本修复了复活末影龙时无限增高柱子

**Comment by 1343008086** [comment]
我想知道在哪个版本修复了复活末影龙时无限增高柱子,更新日志貌似没有写，以前的issue也没了

**Comment by Kasualix** [comment]
最新的这个版本

**Comment by Kasualix** [comment]
那个bug一直有点玄学，老版本里我有时能复现有时又不能，其实我也不太确定到底有没有修好（
